#K-fold cross validation

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [2]:
from sklearn.ensemble import StackingRegressor
level0=list()
level0.append(('lr',LinearRegression()))
level0.append(('dt',DecisionTreeRegressor()))
level1=LinearRegression()
model_en=StackingRegressor(estimators=level0,final_estimator=level1,cv=5)

### diabetes dataset

In [3]:
from sklearn.datasets import load_diabetes

In [4]:
X,y=load_diabetes(return_X_y=True)

In [6]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [7]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [8]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca1=pca.fit_transform(X)
pca1

array([[ 2.79306207e-02, -9.26011612e-02],
       [-1.34686052e-01,  6.52634060e-02],
       [ 1.29447396e-02, -7.77641691e-02],
       [ 2.34543980e-03,  1.81819367e-02],
       [-3.59806910e-02,  3.86213572e-02],
       [-1.88660280e-01, -1.81251413e-02],
       [-9.48347610e-02, -3.83155499e-02],
       [ 9.87389258e-02,  8.69453424e-02],
       [ 2.86833351e-02, -4.19169143e-02],
       [-1.00910711e-02, -2.34450670e-02],
       [-1.83419418e-01, -7.28738089e-02],
       [ 1.88796730e-02, -3.00873701e-02],
       [-7.59323171e-02,  4.66838722e-02],
       [ 1.51473512e-02, -3.09692487e-02],
       [-8.01694940e-02,  8.64707740e-02],
       [ 1.40488092e-01,  4.51897240e-02],
       [ 7.58600302e-03,  4.33946961e-02],
       [ 1.08839198e-01, -7.06819254e-03],
       [-5.49947993e-02, -2.03725705e-02],
       [-8.42651351e-02,  4.41806793e-02],
       [-9.55955468e-02, -1.37941404e-02],
       [-9.18719735e-02, -3.95423697e-02],
       [-7.97268029e-02,  3.42316116e-02],
       [ 1.

In [9]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
for train,test in kf.split(X,y):
    Xtrain,Xtest=X[train],X[test]
    ytrain,ytest=y[train],y[test]

In [10]:
print(Xtrain.shape,ytrain.shape)
print(Xtest.shape,ytest.shape)

(354, 10) (354,)
(88, 10) (88,)


In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(Xtrain,ytrain)

LinearRegression()

In [12]:
ypred=model.predict(Xtest)
ypred

array([191.42755525, 133.04877448,  91.97677251, 198.85251886,
        54.98917741, 173.71496126, 196.45853504, 120.51068765,
       233.23043101, 163.51698175, 161.25297652, 163.87635245,
       253.65571515, 255.59408899, 197.81068341, 185.44645028,
        60.136369  , 194.75215437, 109.34153649, 143.03292209,
       127.92878888, 176.04394067, 209.93507631, 166.33590143,
       162.17984648, 137.52983423, 174.20311213,  74.27388858,
       249.47602759, 113.96862315, 108.93850616, 138.30775304,
       110.87297284,  95.73780182, 159.50300881,  75.56060774,
       254.52713294,  57.2151258 ,  99.57030731, 101.80895415,
       261.24938284, 168.81352273,  64.20043431, 183.10714025,
       169.90316133, 187.00854392, 184.8058785 ,  90.37629602,
       148.74592464, 251.58873636, 198.12771061, 279.87044377,
        51.41253122, 175.31773735, 201.50171976, 170.2097595 ,
       155.29608618, 152.87506316, 232.74795372, 122.87668768,
       163.18303141, 172.87883213, 225.2838219 , 152.36

In [13]:
from sklearn import metrics
import numpy as np
print("Mean Absolute Error= ",metrics.mean_absolute_error(ypred,ytest))
print("Mean Squared Error= ",metrics.mean_squared_error(ypred,ytest))
print("Root Mean Square Error= ",np.sqrt(metrics.mean_absolute_error(ypred,ytest)))

Mean Absolute Error=  42.38729269073616
Mean Squared Error=  2910.2069332665283
Root Mean Square Error=  6.5105524105667225


### digits dataset

In [14]:
from sklearn.datasets import load_digits
digits=load_digits()
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [15]:
X=digits.data
y=digits.target

In [16]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [17]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [18]:
import pandas as pd
df_x=pd.DataFrame(X)
df_x

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [19]:
df_y=pd.DataFrame(y)
df_y

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [20]:
data=pd.concat([df_x,df_y],axis=1)
data

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  0   
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0   0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0   1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0   2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0   3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0   4  
...   ...  ...   ...   ...   ...  ...  ...  ..  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0   9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0   0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0   8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0   9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0   8  

[1797 rows x 65 columns]

In [21]:
data.shape

(1797, 65)

In [22]:
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
60    0
61    0
62    0
63    0
0     0
Length: 65, dtype: int64

In [23]:
digits=load_digits(as_frame=True)
print(digits)
type(digits)

{'data':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        

sklearn.utils.Bunch

In [25]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df_x=scaler.fit_transform(df_x)
df_x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [26]:
from sklearn.decomposition import PCA
pca=PCA(n_components=30)
pca=pca.fit_transform(df_x)
pca

array([[ 1.91421337, -0.95450306, -3.94603302, ...,  0.14782503,
         0.3755493 , -0.3592217 ],
       [ 0.5889797 ,  0.92464126,  3.92475394, ..., -0.69140162,
        -0.88844422, -0.27990373],
       [ 1.30203855, -0.31718809,  3.02333356, ...,  0.23271457,
        -0.39663112,  1.20990037],
       ...,
       [ 1.02259712, -0.14791826,  2.46997493, ..., -0.36949946,
         0.53803194, -0.28578015],
       [ 1.07605483, -0.38090253, -2.45548861, ...,  0.98683818,
         0.2680352 , -0.68146589],
       [-1.25770178, -2.22759796,  0.2836307 , ...,  0.89518109,
         0.48276346,  0.2502851 ]])

In [27]:
pca.shape

(1797, 30)

In [28]:
df_x=pd.DataFrame(pca)
df_x

0         1         2         3         4         5         6   \
0     1.914213 -0.954503 -3.946033  2.028712 -0.267155  0.530349 -1.415352   
1     0.588980  0.924641  3.924754 -1.779833 -0.993393 -0.675658  1.878716   
2     1.302039 -0.317188  3.023334 -2.043378 -2.081147  0.935027 -1.296189   
3    -3.020770 -0.868777 -0.801744 -2.187051 -0.556863  0.727051  0.959624   
4     4.528950 -1.093476  0.973121 -1.419496 -1.715083  1.431685  1.073718   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.104331  0.255026 -3.765862 -1.947000 -0.190091 -0.555737  0.531263   
1793  2.423234 -1.429608 -3.045247  2.632103 -0.822890  0.004110 -1.106795   
1794  1.022597 -0.147918  2.469975 -0.620332 -0.972086 -0.007393  0.380926   
1795  1.076055 -0.380903 -2.455489 -1.312001  0.253550 -0.638350  1.034575   
1796 -1.257702 -2.227598  0.283631 -0.127104 -1.570201  2.342894 -0.383284   

            7         8         9   ...        20        21        22  \
0     1.496145  0.124791 -0.822320  ...  0.447651  0.561182  0.506893   
1     0.556282  1.080227  0.087300  ...  0.929340 -0.249210 -0.500910   
2     1.156075  0.785644 -1.099447  ... -0.520844  0.070570 -1.266533   
3    -1.382599  0.258731  0.744564  ...  0.548498 -0.163204  0.603350   
4    -0.968282 -1.659937  1.174602  ...  0.502858 -0.189006  0.936256   
...        ...       ...       ...  ...       ...       ...       ...   
1792  0.476483  1.152507 -0.473008  ...  0.032574 -0.785341 -0.685013   
1793  2.330917  0.569631 -1.654028  ... -0.953280 -0.044916  0.366747   
1794  0.529011  2.054395 -2.036664  ...  0.142164 -0.232408  0.071072   
1795  0.763316  1.077651 -0.334619  ... -0.121270 -0.438930  1.101828   
1796 -1.200523  0.816353 -1.825523  ... -1.137876 -0.281057 -1.039424   

            23        24        25        26        27        28        29  
0    -0.757129 -0.475411  0.741723  0.289528  0.147825  0.375549 -0.359222  
1     0.487407  0.809915  0.035671 -1.516102 -0.691402 -0.888444 -0.279904  
2    -0.387632 -0.390569 -0.129349  0.311288  0.232715 -0.396631  1.209900  
3    -0.541514 -0.092229 -0.439220  0.086361 -0.444218  0.193085 -1.294484  
4    -0.184199  0.554401 -2.157582  0.116266  0.745956  1.182588  0.348046  
...        ...       ...       ...       ...       ...       ...       ...  
1792 -0.046280 -0.364485 -0.072710  0.194690  0.046453  1.033725 -0.090178  
1793  0.081741  0.205572 -0.870408  0.335670 -0.561315 -0.691824  0.023170  
1794  0.247994 -0.262581 -1.315490 -0.019221 -0.369499  0.538032 -0.285780  
1795  0.301213 -0.930081  1.147865 -0.691112  0.986838  0.268035 -0.681466  
1796 -0.266996 -0.916214 -0.410403 -0.389276  0.895181  0.482763  0.250285  

[1797 rows x 30 columns]

In [29]:
df_y

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [30]:
data=pd.concat([df_x,df_y],axis=1)
data

0         1         2         3         4         5         6   \
0     1.914213 -0.954503 -3.946033  2.028712 -0.267155  0.530349 -1.415352   
1     0.588980  0.924641  3.924754 -1.779833 -0.993393 -0.675658  1.878716   
2     1.302039 -0.317188  3.023334 -2.043378 -2.081147  0.935027 -1.296189   
3    -3.020770 -0.868777 -0.801744 -2.187051 -0.556863  0.727051  0.959624   
4     4.528950 -1.093476  0.973121 -1.419496 -1.715083  1.431685  1.073718   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.104331  0.255026 -3.765862 -1.947000 -0.190091 -0.555737  0.531263   
1793  2.423234 -1.429608 -3.045247  2.632103 -0.822890  0.004110 -1.106795   
1794  1.022597 -0.147918  2.469975 -0.620332 -0.972086 -0.007393  0.380926   
1795  1.076055 -0.380903 -2.455489 -1.312001  0.253550 -0.638350  1.034575   
1796 -1.257702 -2.227598  0.283631 -0.127104 -1.570201  2.342894 -0.383284   

            7         8         9   ...        21        22        23  \
0     1.496145  0.124791 -0.822320  ...  0.561182  0.506893 -0.757129   
1     0.556282  1.080227  0.087300  ... -0.249210 -0.500910  0.487407   
2     1.156075  0.785644 -1.099447  ...  0.070570 -1.266533 -0.387632   
3    -1.382599  0.258731  0.744564  ... -0.163204  0.603350 -0.541514   
4    -0.968282 -1.659937  1.174602  ... -0.189006  0.936256 -0.184199   
...        ...       ...       ...  ...       ...       ...       ...   
1792  0.476483  1.152507 -0.473008  ... -0.785341 -0.685013 -0.046280   
1793  2.330917  0.569631 -1.654028  ... -0.044916  0.366747  0.081741   
1794  0.529011  2.054395 -2.036664  ... -0.232408  0.071072  0.247994   
1795  0.763316  1.077651 -0.334619  ... -0.438930  1.101828  0.301213   
1796 -1.200523  0.816353 -1.825523  ... -0.281057 -1.039424 -0.266996   

            24        25        26        27        28        29  0   
0    -0.475411  0.741723  0.289528  0.147825  0.375549 -0.359222   0  
1     0.809915  0.035671 -1.516102 -0.691402 -0.888444 -0.279904   1  
2    -0.390569 -0.129349  0.311288  0.232715 -0.396631  1.209900   2  
3    -0.092229 -0.439220  0.086361 -0.444218  0.193085 -1.294484   3  
4     0.554401 -2.157582  0.116266  0.745956  1.182588  0.348046   4  
...        ...       ...       ...       ...       ...       ...  ..  
1792 -0.364485 -0.072710  0.194690  0.046453  1.033725 -0.090178   9  
1793  0.205572 -0.870408  0.335670 -0.561315 -0.691824  0.023170   0  
1794 -0.262581 -1.315490 -0.019221 -0.369499  0.538032 -0.285780   8  
1795 -0.930081  1.147865 -0.691112  0.986838  0.268035 -0.681466   9  
1796 -0.916214 -0.410403 -0.389276  0.895181  0.482763  0.250285   8  

[1797 rows x 31 columns]