### steps to follow while creating a machine learning model:
- data collection : use existing datasets(secondary/synthetic dataset - std datasets available publically) or collect data from users(primary dataset) => to show the performance of the created model

- data pre-processing : to enhance the performance of the model
- data segmentation 
- feature extraction or feature selection - together they are known as feature engineering
- classification
- performance measure of the proposed model

# IRIS Dataset

scikit learn (library)
Most popular and simplest dataset

### importing iris dataset

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris)               #mapping : setosa - 0 versicolor - 1 verginica - 2 (target name/ class)
                          #[sepal_ht, sepal_wd, petal_ht, petal_wd]

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [ ]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
print(type(iris))

<class 'sklearn.utils.Bunch'>
<class 'sklearn.utils.Bunch'>


In [ ]:
print(type(iris.data))     #n-dimensional array

<class 'numpy.ndarray'>


In [ ]:
print(type(iris.target))

<class 'numpy.ndarray'>


In [ ]:
print(iris.data.shape)    #150 instances (rows) 4 features (columns)

(150, 4)


In [ ]:
print(iris.target.shape)   #150, 1

(150,)


In [ ]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
X = iris.data         #x contains all the features
y = iris.target
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

preprocessing the data to bring them in a the same range, so they become comparable

uniformaly distributed and normally/biased distributed

bell shaped curve : uniformly distributed (bw either -1 to +1 or 0 to 1 range)

## pre-processing

## Linear transformation

### standard scaler technique (-1 to +1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

### fit and transform methods : proper scaling of the data

In [ ]:
print(scaler.fit(X))
print(scaler.transform(X))         #outliars also possible

StandardScaler()
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138

### MinMax scaler technique (0 to +1 range)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit_transform(X))

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

### MaxAbsoluteScaler technique

In [ ]:
from sklearn.preprocessing import MaxAbsScaler
X,y = load_iris(return_X_y=True)
scaler = MaxAbsScaler()
print(scaler.fit_transform(X))

[[0.64556962 0.79545455 0.20289855 0.08      ]
 [0.62025316 0.68181818 0.20289855 0.08      ]
 [0.59493671 0.72727273 0.1884058  0.08      ]
 [0.58227848 0.70454545 0.2173913  0.08      ]
 [0.63291139 0.81818182 0.20289855 0.08      ]
 [0.6835443  0.88636364 0.24637681 0.16      ]
 [0.58227848 0.77272727 0.20289855 0.12      ]
 [0.63291139 0.77272727 0.2173913  0.08      ]
 [0.55696203 0.65909091 0.20289855 0.08      ]
 [0.62025316 0.70454545 0.2173913  0.04      ]
 [0.6835443  0.84090909 0.2173913  0.08      ]
 [0.60759494 0.77272727 0.23188406 0.08      ]
 [0.60759494 0.68181818 0.20289855 0.04      ]
 [0.5443038  0.68181818 0.15942029 0.04      ]
 [0.73417722 0.90909091 0.17391304 0.08      ]
 [0.72151899 1.         0.2173913  0.16      ]
 [0.6835443  0.88636364 0.1884058  0.16      ]
 [0.64556962 0.79545455 0.20289855 0.12      ]
 [0.72151899 0.86363636 0.24637681 0.12      ]
 [0.64556962 0.86363636 0.2173913  0.12      ]
 [0.6835443  0.77272727 0.24637681 0.08      ]
 [0.64556962 

standard scalar
- z = [(x-x.mean)/std_deviation]

MinMaxScalar
- x = [(value-min)/(max-min)]

# Non Linear Transformation

### Quantile transformation

In [ ]:
from sklearn.preprocessing import QuantileTransformer
Quantile_Transformer = QuantileTransformer(random_state=0)        #--> state value is the seed value (the value we provided in the beginning to the model)
print(Quantile_Transformer.fit_transform(X))

[[0.24161074 0.8557047  0.11409396 0.12751678]
 [0.12416107 0.46644295 0.11409396 0.12751678]
 [0.06375839 0.67114094 0.04697987 0.12751678]
 [0.04362416 0.59060403 0.20134228 0.12751678]
 [0.17785235 0.88926174 0.11409396 0.12751678]
 [0.32550336 0.96979866 0.30536913 0.29530201]
 [0.04362416 0.79530201 0.11409396 0.24832215]
 [0.17785235 0.79530201 0.20134228 0.12751678]
 [0.01342282 0.34563758 0.11409396 0.12751678]
 [0.12416107 0.59060403 0.20134228 0.        ]
 [0.32550336 0.90939597 0.20134228 0.12751678]
 [0.08724832 0.79530201 0.26845638 0.12751678]
 [0.08724832 0.46644295 0.11409396 0.        ]
 [0.         0.46644295 0.00671141 0.        ]
 [0.51006711 0.97986577 0.01677852 0.12751678]
 [0.45973154 1.         0.20134228 0.29530201]
 [0.32550336 0.96979866 0.04697987 0.29530201]
 [0.24161074 0.8557047  0.11409396 0.24832215]
 [0.45973154 0.94295302 0.30536913 0.24832215]
 [0.24161074 0.94295302 0.20134228 0.24832215]
 [0.32550336 0.79530201 0.30536913 0.12751678]
 [0.24161074 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


In [ ]:
from sklearn.preprocessing import QuantileTransformer
Quantile_Transformer = QuantileTransformer()        
print(Quantile_Transformer.fit_transform(X))

[[0.24161074 0.8557047  0.11409396 0.12751678]
 [0.12416107 0.46644295 0.11409396 0.12751678]
 [0.06375839 0.67114094 0.04697987 0.12751678]
 [0.04362416 0.59060403 0.20134228 0.12751678]
 [0.17785235 0.88926174 0.11409396 0.12751678]
 [0.32550336 0.96979866 0.30536913 0.29530201]
 [0.04362416 0.79530201 0.11409396 0.24832215]
 [0.17785235 0.79530201 0.20134228 0.12751678]
 [0.01342282 0.34563758 0.11409396 0.12751678]
 [0.12416107 0.59060403 0.20134228 0.        ]
 [0.32550336 0.90939597 0.20134228 0.12751678]
 [0.08724832 0.79530201 0.26845638 0.12751678]
 [0.08724832 0.46644295 0.11409396 0.        ]
 [0.         0.46644295 0.00671141 0.        ]
 [0.51006711 0.97986577 0.01677852 0.12751678]
 [0.45973154 1.         0.20134228 0.29530201]
 [0.32550336 0.96979866 0.04697987 0.29530201]
 [0.24161074 0.8557047  0.11409396 0.24832215]
 [0.45973154 0.94295302 0.30536913 0.24832215]
 [0.24161074 0.94295302 0.20134228 0.24832215]
 [0.32550336 0.79530201 0.30536913 0.12751678]
 [0.24161074 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


In [ ]:
from sklearn.preprocessing import QuantileTransformer
Quantile_Transformer = QuantileTransformer(random_state=0)        
print(Quantile_Transformer.fit_transform(X))

[[0.24161074 0.8557047  0.11409396 0.12751678]
 [0.12416107 0.46644295 0.11409396 0.12751678]
 [0.06375839 0.67114094 0.04697987 0.12751678]
 [0.04362416 0.59060403 0.20134228 0.12751678]
 [0.17785235 0.88926174 0.11409396 0.12751678]
 [0.32550336 0.96979866 0.30536913 0.29530201]
 [0.04362416 0.79530201 0.11409396 0.24832215]
 [0.17785235 0.79530201 0.20134228 0.12751678]
 [0.01342282 0.34563758 0.11409396 0.12751678]
 [0.12416107 0.59060403 0.20134228 0.        ]
 [0.32550336 0.90939597 0.20134228 0.12751678]
 [0.08724832 0.79530201 0.26845638 0.12751678]
 [0.08724832 0.46644295 0.11409396 0.        ]
 [0.         0.46644295 0.00671141 0.        ]
 [0.51006711 0.97986577 0.01677852 0.12751678]
 [0.45973154 1.         0.20134228 0.29530201]
 [0.32550336 0.96979866 0.04697987 0.29530201]
 [0.24161074 0.8557047  0.11409396 0.24832215]
 [0.45973154 0.94295302 0.30536913 0.24832215]
 [0.24161074 0.94295302 0.20134228 0.24832215]
 [0.32550336 0.79530201 0.30536913 0.12751678]
 [0.24161074 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


splitting the original dataset into two parts - some X (and y corresponding to these X)for training and some for testing


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)   #out of 150 rows, 30%(0.30) is for testing and rest for training(70%)
print(X_train.shape, y_train.shape)                                                          #this random_state values chooses these rows randomly, that's why 0 is assigned
print(X_test.shape, y_test.shape)                                                            #while testing, it has to take the same rows for testing and training. so to restrict the model to this condition, we set the random_state. so it can be any integer value
                                                                                            #same random selection everytime

(105, 4) (105,)
(45, 4) (45,)


In [ ]:
from sklearn.preprocessing import QuantileTransformer
Quantile_Transformer = QuantileTransformer(random_state=0)         #this random_state value has to be the same as the above random_state value (so zero)
print(Quantile_Transformer.fit_transform(X_train))

[[0.17307692 0.         0.35096154 0.34615385]
 [0.74038462 0.44230769 0.79807692 0.69711538]
 [0.8125     0.74519231 0.85576923 1.        ]
 [0.5625     0.01442308 0.66826923 0.58173077]
 [0.8125     0.12019231 0.87980769 0.69711538]
 [0.39903846 0.12019231 0.39903846 0.37980769]
 [0.97596154 0.44230769 0.94230769 0.93269231]
 [0.64903846 0.74519231 0.59134615 0.62019231]
 [0.35576923 0.06730769 0.38461538 0.37980769]
 [0.64903846 0.21153846 0.62980769 0.69711538]
 [0.64903846 0.27403846 0.71153846 0.58173077]
 [0.125      0.12019231 0.54326923 0.64903846]
 [0.64903846 0.12019231 0.66826923 0.75961538]
 [0.89423077 0.67307692 0.59134615 0.54326923]
 [0.74038462 0.44230769 0.74519231 0.80769231]
 [0.5625     0.81730769 0.54326923 0.62019231]
 [0.08653846 0.58173077 0.26442308 0.13461538]
 [0.50961538 0.21153846 0.71153846 0.75961538]
 [0.39903846 0.21153846 0.47115385 0.46634615]
 [0.39903846 0.32692308 0.36538462 0.46634615]
 [0.35576923 0.12019231 0.41346154 0.46634615]
 [0.58653846 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (105). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


- type(iris)
- iris.data
- iris.target
- type(iris.data)
- type(iris.target)
- iris.data.shape
- iris.target_names
- iris.feature_names