In [ ]:
from google.colab import files
uploaded = files.upload()

Saving insurance.csv to insurance.csv


In [ ]:
import pandas as pd
import numpy as np
import io
df = pd.read_csv(io.BytesIO(uploaded['insurance.csv']))         #6 features(age, sex, bmi, children, smoker, region). AND target- charges
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.shape    #7 columns, witout the index and 1338 total rows

(1338, 7)

In [ ]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df.isnull()   #false - no missing value

age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [ ]:
df.isnull().sum()   #to check for every feature. 0 means no missing values in that column

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

### One-hot-encoder method for data- preprocessing

converting values to numeric value for preprocessing
e.g. - smoker is either yes or no. so there will be two diff variables and 0 and 1 will be represented depending on whether the person is a non-smoker or smoker

In [ ]:
#taking categorical columns - sex, smoker and region
categorical_values = ['sex',  'smoker', 'region']
df_encoder = pd.get_dummies(data=df, prefix='OHE', prefix_sep='_', columns=categorical_values, drop_first=True, dtype='int8')   #drop_first drops the index
df_encoder                                                                                                                       #data type = integer - 8 bytes (int8)

#OHE_yes is for smoker. if 1 => smoker. if 0 => non-smoker

age     bmi  children  ...  OHE_northwest  OHE_southeast  OHE_southwest
0      19  27.900         0  ...              0              0              1
1      18  33.770         1  ...              0              1              0
2      28  33.000         3  ...              0              1              0
3      33  22.705         0  ...              1              0              0
4      32  28.880         0  ...              1              0              0
...   ...     ...       ...  ...            ...            ...            ...
1333   50  30.970         3  ...              1              0              0
1334   18  31.920         0  ...              0              0              0
1335   18  36.850         0  ...              0              1              0
1336   21  25.800         0  ...              0              0              1
1337   61  29.070         0  ...              1              0              0

[1338 rows x 9 columns]

In [ ]:
x = df_encoder.drop(['charges'], axis=1)   #x contains all the features. dropping the 'charges' column - axis=1 specifies that we want to drop the entire column
y= df_encoder['charges']   #y contains the target
print(x.shape, y.shape)

(1338, 8) (1338,)


### including children for OHE too

In [ ]:
categorical_values = ['sex',  'smoker', 'region', 'children']
df_encoder = pd.get_dummies(data=df, prefix='OHE', prefix_sep='_', columns=categorical_values, drop_first=True, dtype='int8')   
df_encoder        

age     bmi      charges  OHE_male  ...  OHE_2  OHE_3  OHE_4  OHE_5
0      19  27.900  16884.92400         0  ...      0      0      0      0
1      18  33.770   1725.55230         1  ...      0      0      0      0
2      28  33.000   4449.46200         1  ...      0      1      0      0
3      33  22.705  21984.47061         1  ...      0      0      0      0
4      32  28.880   3866.85520         1  ...      0      0      0      0
...   ...     ...          ...       ...  ...    ...    ...    ...    ...
1333   50  30.970  10600.54830         1  ...      0      1      0      0
1334   18  31.920   2205.98080         0  ...      0      0      0      0
1335   18  36.850   1629.83350         0  ...      0      0      0      0
1336   21  25.800   2007.94500         0  ...      0      0      0      0
1337   61  29.070  29141.36030         0  ...      0      0      0      0

[1338 rows x 13 columns]

In [ ]:
x = df_encoder.drop(['charges'], axis=1) 
y= df_encoder['charges']   
print(x.shape, y.shape)

(1338, 12) (1338,)


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_new = scaler.fit_transform(x)
print(x_new)
print(x_new.shape)

[[-1.43876426 -0.45332    -1.0105187  ... -0.3646069  -0.13798683
  -0.11677484]
 [-1.50996545  0.5096211   0.98959079 ... -0.3646069  -0.13798683
  -0.11677484]
 [-0.79795355  0.38330685  0.98959079 ...  2.74267989 -0.13798683
  -0.11677484]
 ...
 [-1.50996545  1.0148781  -1.0105187  ... -0.3646069  -0.13798683
  -0.11677484]
 [-1.29636188 -0.79781341 -1.0105187  ... -0.3646069  -0.13798683
  -0.11677484]
 [ 1.55168573 -0.26138796 -1.0105187  ... -0.3646069  -0.13798683
  -0.11677484]]
(1338, 12)


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)          #selects the most relevant features only
pc = pca.fit_transform(x_new)
pc

array([[-0.56918067,  1.4646161 ,  0.62651391, -0.30935032],
       [ 1.85067487, -0.00371987, -1.82285487, -0.70143844],
       [ 1.32131493, -0.74714361,  0.49551766,  2.18267563],
       ...,
       [ 1.70861273, -0.38070126, -0.12930568, -0.43384528],
       [-1.05192445,  1.80585799,  0.3145553 , -0.51548652],
       [-1.05275154, -1.44933839, -0.04347471,  0.59109422]])

### training and testing

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(pc, y, test_size=0.30, random_state=0)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(936, 4) (936,)
(402, 4) (402,)


In [ ]:
from sklearn.tree import DecisionTreeRegressor
model_DT_Reg = DecisionTreeRegressor()
model_DT_Reg.fit(x_train, y_train)

DecisionTreeRegressor()

In [ ]:
print(x_test)

[[-0.19064575  2.18780391 -1.07431124  0.07714263]
 [ 1.44631794  0.04360129 -1.82553649 -0.22694648]
 [-0.04129562 -2.01862281  1.64515415 -0.69786625]
 ...
 [ 2.15770534 -0.41237641  0.14831206  0.51085763]
 [ 2.46873929  0.00518072 -1.48367519  0.45045632]
 [-0.941923    1.81529673  0.50601887  0.38893388]]


In [ ]:
print(y_test)

578      9724.53000
610      8547.69130
569     45702.02235
1034    12950.07120
198      9644.25250
           ...     
1261     3277.16100
494     17942.10600
97      10226.28420
418     14418.28040
920     13451.12200
Name: charges, Length: 402, dtype: float64


In [ ]:
y_pred = model_DT_Reg.predict(x_test)
y_pred

array([ 8062.764   ,  7742.1098  , 34303.1672  , 11743.9341  ,
        8988.15875 , 28340.18885 ,  1705.6245  ,  6128.79745 ,
        6128.79745 ,  6548.19505 ,  7228.21565 , 10156.7832  ,
        8930.93455 ,  3757.8448  , 55135.40209 ,  6184.2994  ,
       12124.9924  , 20277.80751 ,  6203.90175 ,  1984.4533  ,
       17748.5062  , 10848.1343  , 11286.5387  , 19539.243   ,
        1532.4697  , 37701.8768  ,  2585.85065 , 27322.73386 ,
        3757.8448  ,  8116.26885 ,  7281.5056  , 44501.3982  ,
       11299.343   , 11365.952   , 15518.18025 ,  3213.62205 ,
        5846.9176  , 21082.16    , 21880.82    ,  1748.774   ,
        4992.3764  ,  3972.9247  , 37270.1512  , 34303.1672  ,
        2166.732   ,  3579.8287  ,  6184.2994  ,  5630.45785 ,
        4719.52405 ,  8871.1517  ,  2211.13075 ,  4466.6214  ,
       25656.57526 , 48549.17835 , 11093.6229  , 12404.8791  ,
        2480.9791  ,  9863.4718  ,  8582.3023  , 30166.61817 ,
        2250.8352  , 46130.5265  , 43753.33705 ,  8968.

In [ ]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values  Predicted Values
578    9724.53000        8062.76400
610    8547.69130        7742.10980
569   45702.02235       34303.16720
1034  12950.07120       11743.93410
198    9644.25250        8988.15875
...           ...               ...
1261   3277.16100        4076.49700
494   17942.10600        6059.17300
97    10226.28420       10982.50130
418   14418.28040        9058.73030
920   13451.12200       12233.82800

[402 rows x 2 columns]

In [ ]:
#score of the model
model_score = model_DT_Reg.score(x_test, y_test)
model_score

0.3098357216274322

### LOADING DATA FROM A FILE

import pandas as pd
insurance = pd.read_csv("../input/insurance/insurance.csv")
insurance

- insurance.columns

- insurance.dtypes

- insurance.shape

- insurance.head(75)

- insurance.describe()

- insurance.isnull()

- insurance.isnull().sum()