##feature-scaling

### 4 types -:
- Standard Scaler
- Min max
- Quantile 
- Absolute max

In [3]:
#STANDARD SCALER

from sklearn.preprocessing import StandardScaler
arr = [[31, 67, 98], [54, 99, 1900], [1, -999, 765]]
sc = StandardScaler()
res = sc.fit_transform(arr)
print(sc.mean_)
print(sc.scale_)
print(res)

[  28.66666667 -277.66666667  921.        ]
[ 21.6999744  510.22696475 743.8875363 ]
[[ 0.10752701  0.67551637 -1.10635003]
 [ 1.16743609  0.73823356  1.31605915]
 [-1.2749631  -1.41374993 -0.20970912]]


In [4]:
#MIN MAX

from sklearn.preprocessing import MinMaxScaler
arr = [[31, 67, 98], [54, 99, 1900], [1, -999, 765]]
sc = MinMaxScaler(feature_range=[3, 10])
res = sc.fit_transform(arr)
# print(sc.mean_)
# print(sc.scale_)
print(res)

[[ 6.96226415  9.79599271  3.        ]
 [10.         10.         10.        ]
 [ 3.          3.          5.59100999]]


In [5]:
#QUANTILE

from sklearn.preprocessing import QuantileTransformer
arr = [[31, 67, 98], [54, 99, 1900], [1, -999, 765]]
sc = QuantileTransformer()
res = sc.fit_transform(arr)
# print(sc.mean_)
# print(sc.scale_)
print(res)

[[0.5 0.5 0. ]
 [1.  1.  1. ]
 [0.  0.  0.5]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (3). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


In [6]:
#MAX ABSOLUTE 

from sklearn.preprocessing import MaxAbsScaler
arr = [[31, 67, 98], [54, 99, 1900], [1, -999, 765]]
sc = MaxAbsScaler()
res = sc.fit_transform(arr)
# print(sc.mean_)
# print(sc.scale_)
print(res)

[[ 0.57407407  0.06706707  0.05157895]
 [ 1.          0.0990991   1.        ]
 [ 0.01851852 -1.          0.40263158]]


##handling-null-values

###Two ways to handle missing values
- drop the corresponding data
- to replace it with mean or median

In [7]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv


In [8]:
import pandas as pd
import numpy as np
import io
df = pd.read_csv(io.BytesIO(uploaded['titanic.csv']))         
df

pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton   
1        1.0       1.0                   Allison, Master. Hudson Trevor   
2        1.0       0.0                     Allison, Miss. Helen Loraine   
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton   
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1305     3.0       0.0                            Zabour, Miss. Thamine   
1306     3.0       0.0                        Zakarian, Mr. Mapriededer   
1307     3.0       0.0                              Zakarian, Mr. Ortin   
1308     3.0       0.0                               Zimmerman, Mr. Leo   
1309     NaN       NaN                                              NaN   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2   
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11   
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN   
1309     NaN      NaN    NaN    NaN     NaN       NaN      NaN      NaN  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  
1309    NaN                              NaN  

[1310 rows x 14 columns]

In [10]:
# 1. drop the missing values

df = df.dropna(axis=1)
df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1310 rows x 0 columns]

In [11]:
# 2. replace it with mean

import numpy as np
from sklearn.impute import SimpleImputer
si = SimpleImputer(missing_values=np.NaN, strategy='constant', fill_value=100)
si.fit_transform([[1,2,3],[4,np.NaN,6],[10,5,9]])

array([[  1.,   2.,   3.],
       [  4., 100.,   6.],
       [ 10.,   5.,   9.]])

In [12]:
# Prepocessing techniques
# Involves formattting and making data clean for better performance of model
# Missing values, Encoding Categorical data: onehot encoder using dummy variables(0 or 1),
# Feature scaling: rescale data to specific range, includes standard scaler, minmaxscaler etc


from sklearn.impute import SimpleImputer
import numpy as np
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
imp=SimpleImputer(missing_values=np.NaN,strategy='mean')
print(imp.fit_transform(X))

[[1.  2.  3. ]
 [4.  4.5 5. ]
 [6.  7.  8. ]]


In [13]:
import pandas as pd
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
df=pd.DataFrame(X)
df

0    1  2
0  1  2.0  3
1  4  NaN  5
2  6  7.0  8

In [14]:
print(df.fillna(10))

   0     1  2
0  1   2.0  3
1  4  10.0  5
2  6   7.0  8


In [15]:
from sklearn.datasets import load_iris
iris=load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [16]:
X,y=load_iris(return_X_y=True)

In [17]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
# data get rescaled such that mean=0 and standard deviation=1
from sklearn.preprocessing import StandardScaler  
scaler=StandardScaler()
print(scaler.fit(X))
print(scaler.transform(X))

StandardScaler()
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138

In [20]:
# data get rescaled between 0-1 range
from sklearn.preprocessing import MinMaxScaler 
scaler=MinMaxScaler()
print(scaler.fit_transform(X))

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [21]:
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
print(scaler.fit_transform(X))

[[0.64556962 0.79545455 0.20289855 0.08      ]
 [0.62025316 0.68181818 0.20289855 0.08      ]
 [0.59493671 0.72727273 0.1884058  0.08      ]
 [0.58227848 0.70454545 0.2173913  0.08      ]
 [0.63291139 0.81818182 0.20289855 0.08      ]
 [0.6835443  0.88636364 0.24637681 0.16      ]
 [0.58227848 0.77272727 0.20289855 0.12      ]
 [0.63291139 0.77272727 0.2173913  0.08      ]
 [0.55696203 0.65909091 0.20289855 0.08      ]
 [0.62025316 0.70454545 0.2173913  0.04      ]
 [0.6835443  0.84090909 0.2173913  0.08      ]
 [0.60759494 0.77272727 0.23188406 0.08      ]
 [0.60759494 0.68181818 0.20289855 0.04      ]
 [0.5443038  0.68181818 0.15942029 0.04      ]
 [0.73417722 0.90909091 0.17391304 0.08      ]
 [0.72151899 1.         0.2173913  0.16      ]
 [0.6835443  0.88636364 0.1884058  0.16      ]
 [0.64556962 0.79545455 0.20289855 0.12      ]
 [0.72151899 0.86363636 0.24637681 0.12      ]
 [0.64556962 0.86363636 0.2173913  0.12      ]
 [0.6835443  0.77272727 0.24637681 0.08      ]
 [0.64556962 

In [22]:
##transform feature to follow normal distribution & reduces outliers
from sklearn.preprocessing import QuantileTransformer 
scaler=QuantileTransformer()
print(scaler.fit_transform(X))

[[0.24161074 0.8557047  0.11409396 0.12751678]
 [0.12416107 0.46644295 0.11409396 0.12751678]
 [0.06375839 0.67114094 0.04697987 0.12751678]
 [0.04362416 0.59060403 0.20134228 0.12751678]
 [0.17785235 0.88926174 0.11409396 0.12751678]
 [0.32550336 0.96979866 0.30536913 0.29530201]
 [0.04362416 0.79530201 0.11409396 0.24832215]
 [0.17785235 0.79530201 0.20134228 0.12751678]
 [0.01342282 0.34563758 0.11409396 0.12751678]
 [0.12416107 0.59060403 0.20134228 0.        ]
 [0.32550336 0.90939597 0.20134228 0.12751678]
 [0.08724832 0.79530201 0.26845638 0.12751678]
 [0.08724832 0.46644295 0.11409396 0.        ]
 [0.         0.46644295 0.00671141 0.        ]
 [0.51006711 0.97986577 0.01677852 0.12751678]
 [0.45973154 1.         0.20134228 0.29530201]
 [0.32550336 0.96979866 0.04697987 0.29530201]
 [0.24161074 0.8557047  0.11409396 0.24832215]
 [0.45973154 0.94295302 0.30536913 0.24832215]
 [0.24161074 0.94295302 0.20134228 0.24832215]
 [0.32550336 0.79530201 0.30536913 0.12751678]
 [0.24161074 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (150). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=47)
print(X_train,y_train)
print(X_test,y_test)

[[6.7 2.5 5.8 1.8]
 [6.1 3.  4.6 1.4]
 [7.3 2.9 6.3 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  3.  4.8 1.8]
 [4.9 3.6 1.4 0.1]
 [4.8 3.4 1.9 0.2]
 [5.  3.3 1.4 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.3 0.3]
 [6.2 2.9 4.3 1.3]
 [5.8 4.  1.2 0.2]
 [6.3 3.3 6.  2.5]
 [5.1 3.4 1.5 0.2]
 [7.7 2.8 6.7 2. ]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [4.8 3.1 1.6 0.2]
 [6.3 2.9 5.6 1.8]
 [6.3 2.5 5.  1.9]
 [4.5 2.3 1.3 0.3]
 [5.  2.  3.5 1. ]
 [6.4 3.2 5.3 2.3]
 [6.6 2.9 4.6 1.3]
 [5.1 3.5 1.4 0.3]
 [4.8 3.  1.4 0.3]
 [5.9 3.  4.2 1.5]
 [6.2 3.4 5.4 2.3]
 [6.8 3.2 5.9 2.3]
 [4.4 3.  1.3 0.2]
 [4.3 3.  1.1 0.1]
 [5.4 3.4 1.7 0.2]
 [6.1 2.9 4.7 1.4]
 [5.  2.3 3.3 1. ]
 [4.7 3.2 1.6 0.2]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.5]
 [7.4 2.8 6.1 1.9]
 [5.6 2.5 3.9 1.1]
 [4.8 3.  1.4 0.1]
 [4.9 2.5 4.5 1.7]
 [6.4 2.8 5.6 2.2]
 [6.4 3.1 5.5 1.8]
 [7.2 3.6 6.1 2.5]
 [5.  3.  1.6 0.2]
 [6.8 2.8 4.8 1.4]
 [4.6 3.4 1.4 0.3]
 [5.8 2.7 3.9 1.2]
 [5.  3.4 1.6 0.4]
 [6.  2.7 5.1 1.6]
 [6.8 3.  5.5 2.1]
 [7.2 3.  5.8 1.6]
 [5.1 2.5 3.

In [24]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


In [25]:
from google.colab import files
uploaded = files.upload()


Saving insurance.csv to insurance.csv


In [26]:
import pandas as pd
import numpy as np
import io
df = pd.read_csv(io.BytesIO(uploaded['insurance.csv']))         

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [28]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [29]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [30]:
categorical_names=['sex','children','smoker','region']
df_encoder=pd.get_dummies(data=df,prefix='OHE',prefix_sep='_',columns=categorical_names,drop_first=True,dtype='int8')
df_encoder

age     bmi      charges  OHE_male  OHE_1  OHE_2  OHE_3  OHE_4  OHE_5  \
0      19  27.900  16884.92400         0      0      0      0      0      0   
1      18  33.770   1725.55230         1      1      0      0      0      0   
2      28  33.000   4449.46200         1      0      0      1      0      0   
3      33  22.705  21984.47061         1      0      0      0      0      0   
4      32  28.880   3866.85520         1      0      0      0      0      0   
...   ...     ...          ...       ...    ...    ...    ...    ...    ...   
1333   50  30.970  10600.54830         1      0      0      1      0      0   
1334   18  31.920   2205.98080         0      0      0      0      0      0   
1335   18  36.850   1629.83350         0      0      0      0      0      0   
1336   21  25.800   2007.94500         0      0      0      0      0      0   
1337   61  29.070  29141.36030         0      0      0      0      0      0   

      OHE_yes  OHE_northwest  OHE_southeast  OHE_southwest  
0           1              0              0              1  
1           0              0              1              0  
2           0              0              1              0  
3           0              1              0              0  
4           0              1              0              0  
...       ...            ...            ...            ...  
1333        0              1              0              0  
1334        0              0              0              0  
1335        0              0              1              0  
1336        0              0              0              1  
1337        1              1              0              0  

[1338 rows x 13 columns]

In [31]:
X=df_encoder.drop(['charges'],axis=1)
X

age     bmi  OHE_male  OHE_1  OHE_2  OHE_3  OHE_4  OHE_5  OHE_yes  \
0      19  27.900         0      0      0      0      0      0        1   
1      18  33.770         1      1      0      0      0      0        0   
2      28  33.000         1      0      0      1      0      0        0   
3      33  22.705         1      0      0      0      0      0        0   
4      32  28.880         1      0      0      0      0      0        0   
...   ...     ...       ...    ...    ...    ...    ...    ...      ...   
1333   50  30.970         1      0      0      1      0      0        0   
1334   18  31.920         0      0      0      0      0      0        0   
1335   18  36.850         0      0      0      0      0      0        0   
1336   21  25.800         0      0      0      0      0      0        0   
1337   61  29.070         0      0      0      0      0      0        1   

      OHE_northwest  OHE_southeast  OHE_southwest  
0                 0              0              1  
1                 0              1              0  
2                 0              1              0  
3                 1              0              0  
4                 1              0              0  
...             ...            ...            ...  
1333              1              0              0  
1334              0              0              0  
1335              0              1              0  
1336              0              0              1  
1337              1              0              0  

[1338 rows x 12 columns]

In [32]:
y=df_encoder['charges']
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [33]:
from sklearn.preprocessing import OneHotEncoder
from numpy import asarray
x=asarray([['male','chrome','from UK',4],['female','safari','from India',5],['female','Opera','from US',6]])
encoder=OneHotEncoder()
output=encoder.fit_transform(x)
print(output)

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (1, 0)	1.0
  (1, 4)	1.0
  (1, 5)	1.0
  (1, 9)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (2, 7)	1.0
  (2, 10)	1.0


In [34]:
from sklearn.preprocessing import OrdinalEncoder
from numpy import asarray
x=asarray([['male','chrome','from UK',4],['female','safari','from India',5],['female','Opera','from US',6]])
encoder=OrdinalEncoder()
output=encoder.fit_transform(x)
print(output)

[[1. 1. 1. 0.]
 [0. 2. 0. 1.]
 [0. 0. 2. 2.]]
